name: Update Zen Browser Version

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release
        id: get_release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/zen-browser/desktop/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          
      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(echo '${{ steps.get_release.outputs.data }}' | jq -r .tag_name)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update flake.nix
        run: |
          sed -i 's/version = "[^"]*"/version = "${{ steps.extract_version.outputs.VERSION }}"/' flake.nix
          # Update the hash specific.sha256
          specific=$(nix-prefetch-url --type sha256 --unpack https://github.com/zen-browser/desktop/releases/download/"${{ steps.extract_version.outputs.VERSION }}"/zen.linux-specific.tar.bz2)
          sed -i "s/specific.sha256 = \".*\"/specific.sha256 = \"$specific\"/" ./flake.nix
          # Update the hash generic.sha256
          generic=$(nix-prefetch-url --type sha256 --unpack https://github.com/zen-browser/desktop/releases/download/"${{ steps.extract_version.outputs.VERSION }}"/zen.linux-generic.tar.bz2)
          sed -i "s/generic.sha256 = \".*\"/generic.sha256 = \"$generic\"/" ./flake.nix
          nix flake update

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Zen Browser to v${{ steps.extract_version.outputs.VERSION }}"
          file_pattern: "*"
